name: simple_tracker
description: A simple daily tracker.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 原有的库
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  # === 新增的两个库 ===
  dynamic_color: ^1.7.0
  webdav_client: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true